import { IMAGES } from './images';

export const SITE_CONFIG = {
  name: 'Marengo Asia Hospitals',
  tagline: 'Patient First | Trusted Care, Every Step',
  emergencyNumber: '1066',
  tollFree: '1800 309 0309',
  internationalHelp: '+91 9999 888 777',
  email: 'care@marengoasiahospitals.com',
  intlEmail: 'international@marengoasiahospitals.com',
  address: 'Marengo Asia Healthcare, Sector 56, Gurugram, Haryana - 122011, India',
};

// Main Desktop Header Navigation Items
export const HEADER_NAV_ITEMS = [
  { label: 'Our Hospital', href: '#hospitals', dropdownType: 'hospitals', hasDropdown: true },
  { label: 'Specialities', href: '#specialties', dropdownType: 'specialties', hasDropdown: true },
  { label: 'Find Doctor', href: '#doctors', dropdownType: null, hasDropdown: false },
  { label: 'Blogs', href: '#blogs', dropdownType: null, hasDropdown: false },
  { label: 'Health Check-Up', href: '#packages', dropdownType: null, hasDropdown: false },
];

// Mega Menu for Our Hospital (Image 1)
export const HOSPITAL_MEGA_MENU = {
  column1: [
    {
      region: 'SURAT',
      items: [
        {
          name: 'Sunshine Global Hospital, Surat',
          subtitle: '(MANAGED BY MARENGO ASIA HOSPITAL)',
          href: '#hospitals',
        },
      ],
    },
    {
      region: 'SAUDI ARABIA',
      items: [
        {
          name: 'Specialized Najran Hospital',
          subtitle: '(OPERATION & MANAGEMENT PARTNERSHIP WITH MARENGO ASIA HOSPITALS)',
          href: '#hospitals',
        },
      ],
    },
  ],
  column2: {
    region: 'DELHI/NCR',
    items: [
      {
        name: 'Marengo Asia Hospitals, Gurugram',
        address: 'Golf Course Ext Rd, Sushant Lok II, Sector 56, Gurugram, Ghata, Haryana 122011',
        href: '#hospitals',
      },
      {
        name: 'Marengo Asia Hospitals, Faridabad',
        address: 'Plot No.1, HUDA Staff Colony, Sector 16, Faridabad, Haryana 121002',
        href: '#hospitals',
      },
    ],
  },
  column3: {
    region: 'AHMEDABAD',
    items: [
      {
        name: 'Marengo CIMS Hospital, Ahmedabad',
        address: 'Off, Science City Rd, Science City, Panchamrut Bunglows II, Sola, Ahmedabad, Gujarat 380060',
        href: '#hospitals',
      },
    ],
  },
  ctaColumn: {
    appointment: {
      title: 'BOOK AN APPOINTMENT',
      description: "Marengo Asia Hospitals is always looking to make things easier for you. Please click on 'Book Now' and fill in the details, we will get back to you.",
      buttonText: 'Book Now',
    },
    findDoctor: {
      title: 'FIND A DOCTOR',
      description: 'Medicines cure diseases but only doctors can cure patients, Click Find Now for the best cure.',
      buttonText: 'Find Now',
      href: '#doctors',
    },
  },
};

// Mega Menu for Specialities (Image 2)
export const SPECIALITIES_MEGA_MENU = {
  centersOfExcellence: {
    title: 'CENTRE OF EXCELLENCE',
    viewAllHref: '#specialties',
    items: [
      { name: 'Cancer Care / Oncology', icon: '🎗️', href: '#specialties' },
      { name: 'Cardiac Sciences', icon: '🫀', href: '#specialties' },
      { name: 'Gastroenterology', icon: '🩺', href: '#specialties' },
      { name: 'Liver Transplant and Biliary Sciences', icon: '🫁', href: '#specialties' },
      { name: 'Orthopaedics & Joint Replacement', icon: '🦴', href: '#specialties' },
      { name: 'Renal Sciences', icon: '🫘', href: '#specialties' },
      { name: 'Neurosciences', icon: '🧠', href: '#specialties' },
    ],
  },
  keySpecialities: {
    title: 'KEY SPECIALITIES',
    viewAllHref: '#specialties',
    items: [
      { name: 'Bone Marrow Transplant', icon: '🧬', href: '#specialties' },
      { name: 'Bariatric Surgery', icon: '⚖️', href: '#specialties' },
      { name: 'Clinical Psychology', icon: '🗣️', href: '#specialties' },
      { name: 'Rheumatology', icon: '🦵', href: '#specialties' },
      { name: 'Diabetic Foot', icon: '🦶', href: '#specialties' },
      { name: 'Dental', icon: '🦷', href: '#specialties' },
      { name: 'Dermatology', icon: '💉', href: '#specialties' },
    ],
  },
  procedures: {
    title: 'PROCEDURES',
    viewAllHref: '#specialties',
    items: [
      { name: 'Medical Oncology', href: '#specialties' },
      { name: 'Surgical Oncology', href: '#specialties' },
      { name: 'Hematology Oncology', href: '#specialties' },
      { name: 'Gynecologic Oncology', href: '#specialties' },
      { name: 'Pediatric Oncology', href: '#specialties' },
    ],
  },
};

export const NAV_LINKS = [
  { label: 'About Us', href: '#about', hasDropdown: true },
  { label: 'Specialties', href: '#specialties', hasDropdown: true },
  { label: 'Hospitals', href: '#hospitals', hasDropdown: true },
  { label: 'International Patients', href: '#international', hasDropdown: false },
  { label: 'Doctors', href: '#doctors', hasDropdown: false },
  { label: 'Academics & Research', href: '#research', hasDropdown: true },
];

export const QUICK_ACTIONS = [
  {
    id: 'doctor',
    title: 'Find a Doctor',
    subtitle: 'Book consult with top specialists',
    icon: 'UserCheck',
    color: 'bg-[#F37023] hover:bg-[#E05D10]',
    textColor: 'text-white',
    href: '#doctors',
  },
  {
    id: 'specialties',
    title: 'Our Specialties',
    subtitle: '30+ Super-speciality departments',
    icon: 'Stethoscope',
    color: 'bg-[#003B73] hover:bg-[#002D59]',
    textColor: 'text-white',
    href: '#specialties',
  },
  {
    id: 'health-checkup',
    title: 'Book Your Health Checkup',
    subtitle: 'Preventive full-body packages',
    icon: 'ClipboardCheck',
    color: 'bg-[#5B7B12] hover:bg-[#4E6A0F]',
    textColor: 'text-white',
    href: '#packages',
  },
  {
    id: 'hospitals',
    title: 'Our Hospitals',
    subtitle: 'State-of-the-art medical centers',
    icon: 'Building2',
    color: 'bg-[#64748B] hover:bg-[#475569]',
    textColor: 'text-white',
    href: '#hospitals',
  },
];

export const CENTERS_OF_EXCELLENCE = [
  {
    id: 'neuro',
    title: 'Neuro Sciences',
    subtitle: 'Brain, Spine & Nerve Care',
    stat: '25,000+',
    statLabel: 'Surgeries',
    icon: 'Brain',
    description: 'Comprehensive neurological care, robotic spinal surgeries, stroke unit & neuro-rehab.',
    color: '#003B73',
  },
  {
    id: 'cancer',
    title: 'Cancer Care / Oncology',
    subtitle: 'Precision Radiotherapy & Surgery',
    stat: '50,000+',
    statLabel: 'Patients Treated',
    icon: 'ActivitySquare',
    description: 'Multidisciplinary tumor board, CyberKnife radiosurgery, immunotherapy & bone marrow transplant.',
    color: '#0284C7',
  },
  {
    id: 'cardiac',
    title: 'Cardiac Sciences',
    subtitle: 'Heart Failure & Angioplasty',
    stat: '100,000+',
    statLabel: 'Procedures',
    icon: 'HeartPulse',
    description: 'Advanced cath labs, minimally invasive cardiac surgery (MICS), TAVI, and heart transplant unit.',
    color: '#E11D48',
  },
  {
    id: 'ortho',
    title: 'Orthopaedics & Joints',
    subtitle: 'Robotic Knee & Hip Replacement',
    stat: '40,000+',
    statLabel: 'Surgeries',
    icon: 'Bone',
    description: 'AI-assisted robotic joint replacement, sports injury arthroscopy, and complex trauma management.',
    color: '#D97706',
  },
  {
    id: 'gastro',
    title: 'Gastroenterology & HPB',
    subtitle: 'Liver & Digestive Sciences',
    stat: '35,000+',
    statLabel: 'Endoscopies',
    icon: 'Crosshair',
    description: 'Advanced therapeutic endoscopy, liver transplant, ERCP and complex GI oncology.',
    color: '#0D9488',
  },
  {
    id: 'renal',
    title: 'Renal Sciences & Urology',
    subtitle: 'Kidney Care & Transplants',
    stat: '30,000+',
    statLabel: 'Dialysis/Procedures',
    icon: 'ShieldAlert',
    description: 'Robotic urology, pediatric nephrology, laser stone removal & ABO-incompatible kidney transplants.',
    color: '#6366F1',
  },
  {
    id: 'mother-child',
    title: 'Mother & Child Care',
    subtitle: 'Obstetrics, Gynaec & NICU',
    stat: '60,000+',
    statLabel: 'Safe Deliveries',
    icon: 'Baby',
    description: 'Level III NICU, high-risk pregnancy management, fetal medicine & advanced gynaecological surgery.',
    color: '#EC4899',
  },
  {
    id: 'pulmo',
    title: 'Pulmonology & Critical Care',
    subtitle: 'Lungs & Sleep Medicine',
    stat: '20,000+',
    statLabel: 'ICU Recoveries',
    icon: 'Wind',
    description: 'Advanced ECMO facility, broncho-alveolar interventions, asthma & sleep apnea clinics.',
    color: '#0284C7',
  },
];

export const SPECIALTY_SEARCH_DATA = {
  letters: ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','#'],
  popular: [
    { label: 'Cardiology', icon: 'Heart', count: '48 Doctors' },
    { label: 'Neurology', icon: 'Brain', count: '32 Doctors' },
    { label: 'Orthopaedics', icon: 'Bone', count: '40 Doctors' },
    { label: 'Oncology', icon: 'ShieldPlus', count: '35 Doctors' },
    { label: 'Gastroenterology', icon: 'Activity', count: '28 Doctors' },
    { label: 'Pediatrics', icon: 'Baby', count: '24 Doctors' },
    { label: 'Nephrology', icon: 'Crosshair', count: '20 Doctors' },
  ],
  dictionary: {
    A: ['Asthma & Allergy', 'Arthritis Care', 'Arrhythmia Management', 'Anaesthesia & Pain Medicine', 'Aneurysm Repair'],
    B: ['Bone Marrow Transplant', 'Brain Tumor Surgery', 'Bariatric & Weight Loss Surgery', 'Bowel Diseases'],
    C: ['Cardiology & Angioplasty', 'Cancer Immunotherapy', 'CyberKnife Radiosurgery', 'Cataract & Eye Care', 'Critical Care Medicine'],
    D: ['Dermatology & Cosmetology', 'Diabetes & Endocrinology', 'Dialysis Care', 'Deep Brain Stimulation'],
    E: ['Emergency & Trauma', 'Endocrinology', 'ENT (Ear Nose Throat)', 'Endoscopic Spine Surgery'],
    F: ['Fetal Medicine', 'Fracture & Trauma Clinic', 'Foot & Ankle Surgery', 'Fertility Support'],
    G: ['Gastroenterology', 'General Surgery', 'Gynaec Oncology', 'Genetics & Genomics'],
    H: ['Heart Transplant', 'Hematology', 'Hepatology (Liver Care)', 'Hernia Repair'],
    I: ['Interventional Cardiology', 'Infectious Diseases', 'IVF & Fertility', 'Intensive Care Unit (ICU)'],
    J: ['Joint Replacement (Robotic)', 'Juvenile Arthritis', 'Jaw & Maxillofacial Care'],
    K: ['Kidney Transplant', 'Knee Arthroscopy', 'Keyhole Surgery', 'Kidney Stone Laser'],
    L: ['Liver Transplant', 'Laparoscopic Surgery', 'Lung Cancer Care', 'Laser Urology'],
    M: ['Mother & Child Care', 'Medical Oncology', 'Minimally Invasive Spine', 'Mammography'],
    N: ['Neurology', 'Neurosurgery', 'Nephrology', 'Neonatology (NICU)', 'Nuclear Medicine'],
    O: ['Oncology (Cancer)', 'Orthopaedics', 'Ophthalmology', 'Organ Transplant', 'Oral Surgery'],
    P: ['Pulmonology', 'Pediatrics', 'Plastic & Reconstructive', 'Psychiatry & Mental Wellness'],
    Q: ['Quality Clinical Audits', 'Quaternary Care Referrals'],
    R: ['Robotic Surgery', 'Radiation Oncology', 'Rheumatology', 'Radiology & Imaging', 'Renal Sciences'],
    S: ['Spine Surgery', 'Surgical Oncology', 'Stroke Emergency Unit', 'Sports Medicine'],
    T: ['TAVI (Aortic Valve)', 'Thoracic Surgery', 'Thyroid Care', 'Trauma Resuscitation'],
    U: ['Urology & Andrology', 'Ultrasound & 4D Scan', 'Uro-Oncology'],
    V: ['Vascular Surgery', 'Varicose Veins Laser', 'Vaccination Clinic'],
    W: ['Women Health Wellness', 'Wound Care & Hyperbaric Oxygen'],
    X: ['X-Ray & Digital Fluoroscopy'],
    Y: ['Youth & Adolescent Wellness'],
    Z: ['Zoonotic Disease Care'],
    '#': ['24/7 Emergency Care', '3T MRI & High-Speed CT', '128-Slice Cardiac CT'],
  },
};

export const TECHNOLOGIES = [
  {
    id: 'pet-ct',
    title: 'PET-CT Technology',
    subtitle: 'Precision Molecular Imaging',
    description: 'High-resolution metabolic scanning enabling ultra-early cancer detection and precise radiation planning.',
    image: IMAGES.technologies.petCt,
    tag: 'Advanced Imaging',
    link: '#',
  },
  {
    id: 'cyberknife',
    title: 'CyberKnife Robotic System',
    subtitle: 'Non-Invasive Radiosurgery',
    description: 'Pioneering robotic radiation system tracking tumors in real-time with sub-millimeter clinical accuracy.',
    image: IMAGES.technologies.cyberknife,
    tag: 'Robotic Oncology',
    link: '#',
  },
  {
    id: 'biplane',
    title: 'Bi-Plane Cath Lab',
    subtitle: 'Next-Gen Angiography',
    description: 'Simultaneous 3D imaging for ultra-fast, low-radiation vascular interventions and acute stroke clot retrieval.',
    image: IMAGES.technologies.biplaneCathlab,
    tag: 'Cardiac & Neuro Suite',
    link: '#',
  },
  {
    id: 'robotic-surgery',
    title: 'Advanced Robotic Surgery',
    subtitle: 'Da Vinci Xi 4th Gen Platform',
    description: 'Multi-quadrant robotic precision offering minimal blood loss, microscopic precision, and rapid recovery.',
    image: IMAGES.technologies.roboticSurgery,
    tag: 'Minimally Invasive',
    link: '#',
  },
];

export const INTERNATIONAL_PATIENTS_DATA = {
  heading: 'International Patients',
  subheading: 'World-Class Healthcare Beyond Borders',
  description: 'Marengo Asia Hospitals welcomes patients from over 30 countries, delivering compassionate clinical excellence, visa assistance, airport transfers, multilingual translators, and personalized concierge care.',
  stats: [
    { value: '3,200,000+', label: 'Patients Treated' },
    { value: '30+', label: 'Countries Served' },
    { value: '1,000+', label: 'Expert Doctors' },
  ],
  countries: [
    { code: 'bd', name: 'Bangladesh', image: IMAGES.countries.bd },
    { code: 'om', name: 'Oman', image: IMAGES.countries.om },
    { code: 'iq', name: 'Iraq', image: IMAGES.countries.iq },
    { code: 'uz', name: 'Uzbekistan', image: IMAGES.countries.uz },
    { code: 'ke', name: 'Kenya', image: IMAGES.countries.ke },
    { code: 'fj', name: 'Fiji', image: IMAGES.countries.fj },
    { code: 'ng', name: 'Nigeria', image: IMAGES.countries.ng },
    { code: 'tz', name: 'Tanzania', image: IMAGES.countries.tz },
    { code: 'mu', name: 'Mauritius', image: IMAGES.countries.mu },
    { code: 'ae', name: 'UAE', image: IMAGES.countries.ae },
    { code: 'ye', name: 'Yemen', image: IMAGES.countries.ye },
    { code: 'mm', name: 'Myanmar', image: IMAGES.countries.mm },
  ],
  features: [
    'Complimentary Medical Opinion & Quotation within 24 Hours',
    'Visa Invitation Letter & Government Healthcare Facilitation',
    'Dedicated International Patient Lounge & Language Translators',
    'Airport Pickup & Drop with Local SIM and Currency Assistance',
  ],
};

export const HEALTH_PACKAGES = [
  {
    id: 'cardiac-pack',
    title: 'Comprehensive Heart Check',
    subtitle: 'Complete Cardiovascular Screening',
    description: 'Lipid Profile, ECG, 2D Echo, TMT, Chest X-Ray, Cardiologist Consultation.',
    originalPrice: '₹8,500',
    discountPrice: '₹3,999',
    testsCount: '24 Parameters',
    image: IMAGES.packages.cardiac,
    badge: 'Popular',
  },
  {
    id: 'executive-pack',
    title: 'Executive Master Health Check',
    subtitle: 'Whole-Body Advanced Diagnostic',
    description: 'Liver, Kidney, Thyroid, HbA1c, Vitamin D/B12, Ultrasound Abdomen & Physician Review.',
    originalPrice: '₹12,000',
    discountPrice: '₹5,499',
    testsCount: '62 Parameters',
    image: IMAGES.packages.executive,
    badge: 'Comprehensive',
  },
  {
    id: 'cancer-pack',
    title: 'Advanced Cancer Screening',
    subtitle: 'Early Detection for Men & Women',
    description: 'Tumor Markers (PSA/CA-125), Mammography/USG, Stool Occult, Oncology Consult.',
    originalPrice: '₹15,000',
    discountPrice: '₹6,999',
    testsCount: '32 Parameters',
    image: IMAGES.packages.cancer,
    badge: 'Specialized',
  },
  {
    id: 'maternity-pack',
    title: 'Maternity & Fetal Wellness',
    subtitle: 'Nurturing Mother & Child Care',
    description: 'Antenatal Screen, 4D Ultrasound, Dual Marker, Nutritional & Gynaecological Review.',
    originalPrice: '₹9,500',
    discountPrice: '₹4,499',
    testsCount: '28 Parameters',
    image: IMAGES.packages.maternity,
    badge: 'Care Package',
  },
];

export const WHY_CHOOSE_US_DATA = {
  heading: 'Why Choose Us',
  subtitle: 'Committed to clinical excellence, compassionate healing, and transparent medical outcomes',
  stats: [
    { value: '32,000,000+', label: 'Patients Healed', icon: 'Users' },
    { value: '10,000+', label: 'Doctors & Caregivers', icon: 'Award' },
    { value: '30+', label: 'Hospitals & Super Speciality Centers', icon: 'Building2' },
    { value: '99.4%', label: 'Clinical Success Rate', icon: 'ShieldCheck' },
  ],
  pillars: [
    {
      title: 'Patient First Culture',
      description: 'Every protocol, decision, and facility is designed around patient comfort, dignity, and rapid recovery.',
      icon: 'HeartHandshake',
    },
    {
      title: 'Global Clinical Standards',
      description: 'NABH and JCI accredited facilities adhering to stringent international infection control measures.',
      icon: 'Sparkles',
    },
    {
      title: 'Cutting-Edge Robotic Platforms',
      description: 'Equipped with Da Vinci Xi, CyberKnife, and Bi-Plane systems for pin-point surgical precision.',
      icon: 'Cpu',
    },
    {
      title: 'Transparent & Ethical Care',
      description: 'Transparent treatment plans, clear cost estimations, and multi-disciplinary tumor board evaluations.',
      icon: 'FileText',
    },
  ],
};

export const PATIENT_STORIES = [
  {
    id: 'story-1',
    patientName: 'Mrs. Sunita Verma',
    location: 'Ahmedabad, India',
    treatment: 'Complex Cardiac Bypass (CABG)',
    doctor: 'Dr. A. K. Banerjee (Chief Cardio-Thoracic Surgeon)',
    rating: 5,
    quote: '"The prompt emergency response and compassionate care given by the Marengo cardiac team gave me a second lease of life. Today I am back to my daily morning walks without any pain!"',
    story: 'Admitted with acute coronary syndrome, Mrs. Verma underwent successful minimally invasive coronary artery bypass surgery and was discharged within 4 days in good health.',
    image: IMAGES.testimonials.patient1,
    hasVideo: true,
  },
  {
    id: 'story-2',
    patientName: 'Sarah Jenkins',
    location: 'Nairobi, Kenya',
    treatment: 'Targeted Oncology & CyberKnife Radiosurgery',
    doctor: 'Dr. Neha Malhotra (Senior Radiation Oncologist)',
    rating: 5,
    quote: '"Traveling across borders for cancer treatment felt overwhelming until we arrived at Marengo Asia. The international patient team made us feel like family from day one."',
    story: 'Sarah completed precise non-invasive stereotactic radiosurgery for a deep seated lesion with zero pain and remarkable tumor shrinkage on follow-up scans.',
    image: IMAGES.testimonials.patient2,
    hasVideo: true,
  },
  {
    id: 'story-3',
    patientName: 'Mr. David Mutua',
    location: 'Suva, Fiji',
    treatment: 'Robotic Bilateral Knee Replacement',
    doctor: 'Dr. Vikram Shah (Director - Orthopaedics)',
    rating: 5,
    quote: '"I had severe degenerative arthritis and could barely stand for 5 minutes. Within 48 hours after robotic surgery at Marengo, I was walking smoothly with a walker!"',
    story: 'Thanks to AI-guided sub-millimeter joint alignment, David experienced minimal postoperative pain and regained full functional mobility ahead of scheduled rehab.',
    image: IMAGES.testimonials.patient3,
    hasVideo: true,
  },
];

export const NEWS_AND_EVENTS = [
  {
    id: 'news-featured',
    title: 'Marengo Asia Hospitals Inaugurates State-of-the-Art Robotic Surgical Hub',
    date: 'May 18, 2026',
    category: 'Innovation & Expansion',
    summary: 'The new robotic center integrates AI-assisted diagnostics, sub-millimeter Da Vinci Xi consoles, and specialized training programs for next-generation surgeons.',
    image: IMAGES.news.main,
    isFeatured: true,
  },
  {
    id: 'news-1',
    title: 'International Oncology Summit: Breakthroughs in Immunotherapy',
    date: 'April 29, 2026',
    category: 'Conference',
    summary: 'Over 500 global oncologists gathered at Marengo to discuss personalized genetic medicine and targeted CAR-T cell therapies.',
    image: IMAGES.news.news1,
  },
  {
    id: 'news-2',
    title: 'New Super-Specialty Wing Inaugurated at Gurugram Hospital',
    date: 'March 14, 2026',
    category: 'Infrastructure',
    summary: 'Adding 150 critical care ICU beds, 4 modular laminar flow OTs, and dedicated pediatric stroke unit.',
    image: IMAGES.news.news2,
  },
  {
    id: 'news-3',
    title: 'Marengo Healthcare Wins National Excellence in Patient Safety Award',
    date: 'February 22, 2026',
    category: 'Accreditation',
    summary: 'Recognized for achieving 99.8% zero hospital-acquired infection benchmarks across all operating facilities.',
    image: IMAGES.news.news3,
  },
  {
    id: 'news-4',
    title: 'Successful Multi-Organ Pediatric Transplant Milestone Achieved',
    date: 'January 10, 2026',
    category: 'Clinical Milestone',
    summary: 'A 24-hour marathon surgery successfully gives an 8-year-old child a healthy new liver and kidney.',
    image: IMAGES.news.news4,
  },
];

export const BLOGS_DATA = [
  {
    id: 'blog-1',
    title: 'Understanding Heart Health: 10 Early Warning Signs You Shouldn’t Ignore',
    category: 'Cardiology',
    date: 'June 02, 2026',
    readTime: '4 min read',
    author: 'Dr. Anya Sharma, Chief Interventional Cardiologist',
    excerpt: 'Chest tightness isn’t the only warning sign of cardiac issues. Learn subtle symptoms like jaw pain, unexplained fatigue, and shortness of breath.',
    image: IMAGES.blogs.cardiac,
  },
  {
    id: 'blog-2',
    title: 'Robotic Joint Replacement: How Precision Technology Reduces Recovery Time',
    category: 'Orthopaedics',
    date: 'May 28, 2026',
    readTime: '5 min read',
    author: 'Dr. Rajesh Patel, Senior Joint Replacement Surgeon',
    excerpt: 'Explore how 3D CT mapping and robotic arms preserve healthy bone tissues, allowing patients to walk on the very same day of surgery.',
    image: IMAGES.blogs.robotic,
  },
  {
    id: 'blog-3',
    title: 'Brain Stroke Protocol: The Golden Hour and Life-Saving Emergency Interventions',
    category: 'Neurology',
    date: 'May 15, 2026',
    readTime: '6 min read',
    author: 'Dr. Vivek Malhotra, Director - Neuro-Interventional Surgery',
    excerpt: 'Recognizing BE-FAST stroke signs and reaching an equipped mechanical thrombectomy center within 4.5 hours can prevent permanent paralysis.',
    image: IMAGES.blogs.brain,
  },
];

export const HOSPITALS_DATA = [
  {
    id: 'ahmedabad',
    name: 'Marengo CIMS Hospital',
    city: 'Ahmedabad',
    state: 'Gujarat',
    address: 'Science City Road, Sola, Ahmedabad',
    beds: '450+ Beds',
    specialties: 'Heart Transplant, Oncology, Robotic Surgery',
    image: IMAGES.hospitals.ahmedabad,
    phone: '+91 79 4805 1000',
  },
  {
    id: 'gurgaon',
    name: 'Marengo Asia Hospital',
    city: 'Gurugram',
    state: 'Haryana',
    address: 'Golf Course Extension Road, Sector 56, Gurugram',
    beds: '350+ Beds',
    specialties: 'Neurosciences, Cardiac, Organ Transplant',
    image: IMAGES.hospitals.gurgaon,
    phone: '+91 124 413 1066',
  },
  {
    id: 'faridabad',
    name: 'Marengo Asia Hospital',
    city: 'Faridabad',
    state: 'Delhi NCR',
    address: 'Sector 16, Faridabad, Haryana',
    beds: '325+ Beds',
    specialties: 'Cancer Care, Orthopaedics, Nephrology',
    image: IMAGES.hospitals.faridabad,
    phone: '+91 129 425 3000',
  },
  {
    id: 'surat',
    name: 'Marengo Specialty Center',
    city: 'Surat',
    state: 'Gujarat',
    address: 'Ring Road, Majura Gate, Surat',
    beds: '200+ Beds',
    specialties: 'Mother & Child, Gastro Sciences, Dialysis',
    image: IMAGES.hospitals.surat,
    phone: '+91 261 270 5000',
  },
  {
    id: 'kolkata',
    name: 'Marengo Health Apex',
    city: 'Kolkata',
    state: 'West Bengal',
    address: 'EM Bypass, Sector V, Salt Lake, Kolkata',
    beds: '280+ Beds',
    specialties: 'Robotic Spine, Oncology, Critical Care',
    image: IMAGES.hospitals.kolkata,
    phone: '+91 33 6622 1000',
  },
  {
    id: 'noida',
    name: 'Marengo Super Speciality',
    city: 'Noida',
    state: 'Uttar Pradesh',
    address: 'Sector 62, Expressway, Noida',
    beds: '300+ Beds',
    specialties: 'Cardiac Cath Lab, Urology, Pulmonology',
    image: IMAGES.hospitals.noida,
    phone: '+91 120 450 8000',
  },
  {
    id: 'mumbai',
    name: 'Marengo Care Hub',
    city: 'Mumbai',
    state: 'Maharashtra',
    address: 'Bandra Kurla Complex (BKC), Mumbai',
    beds: '250+ Beds',
    specialties: 'Advanced Diagnostics, Day Care Surgery',
    image: IMAGES.hospitals.mumbai,
    phone: '+91 22 6900 2000',
  },
  {
    id: 'delhi',
    name: 'Marengo Asia Apex',
    city: 'Delhi NCR',
    state: 'Delhi',
    address: 'Ring Road, South Extension, New Delhi',
    beds: '400+ Beds',
    specialties: 'Organ Transplant, CyberKnife, Trauma',
    image: IMAGES.hospitals.delhi,
    phone: '+91 11 4000 8888',
  },
];

export const FOOTER_SECTIONS = [
  {
    title: 'Patient Care',
    links: [
      { label: 'Find a Doctor', href: '#doctors' },
      { label: 'Book Appointment', href: '#appointment' },
      { label: 'Centers of Excellence', href: '#specialties' },
      { label: 'International Patients', href: '#international' },
      { label: 'Second Medical Opinion', href: '#second-opinion' },
      { label: 'Emergency Services (1066)', href: 'tel:1066' },
      { label: 'Patient Rights & Responsibilities', href: '#legal' },
    ],
  },
  {
    title: 'About Us',
    links: [
      { label: 'About Marengo Asia', href: '#about' },
      { label: 'Leadership & Vision', href: '#leadership' },
      { label: 'Awards & Accreditations', href: '#awards' },
      { label: 'Corporate Social Responsibility', href: '#csr' },
      { label: 'Careers at Marengo', href: '#careers' },
      { label: 'Media & Newsroom', href: '#news' },
      { label: 'Bio-Medical Waste Reports', href: '#waste' },
    ],
  },
  {
    title: 'Manage Your Health',
    links: [
      { label: 'Health Check-Up Packages', href: '#packages' },
      { label: 'Patient Portal Login', href: '#login' },
      { label: 'Download Lab Reports', href: '#reports' },
      { label: 'Pay Hospital Bills Online', href: '#pay-online' },
      { label: 'Health Blogs & Insights', href: '#blogs' },
      { label: 'Medical Insurance & TPA Desk', href: '#insurance' },
    ],
  },
  {
    title: 'Our Hospitals',
    links: [
      { label: 'Ahmedabad - CIMS Hospital', href: '#hospitals' },
      { label: 'Gurugram - Sector 56', href: '#hospitals' },
      { label: 'Faridabad - Sector 16', href: '#hospitals' },
      { label: 'Surat - Specialty Clinic', href: '#hospitals' },
      { label: 'Kolkata - Health Apex', href: '#hospitals' },
      { label: 'Noida - Super Speciality', href: '#hospitals' },
      { label: 'Delhi NCR - Apex Hospital', href: '#hospitals' },
    ],
  },
  {
    title: 'Academics & Research',
    links: [
      { label: 'Clinical Trials & Research', href: '#research' },
      { label: 'DNB & Fellowship Programs', href: '#academics' },
      { label: 'Nursing & Allied Training', href: '#nursing' },
      { label: 'Medical Journal Publications', href: '#publications' },
      { label: 'CME & Academic Conferences', href: '#cme' },
    ],
  },
];
