export const IMAGES = {
  logo: {
    main: '/images/logo/logo.webp',
  },
  hero: {
    home: '/images/hero/home-hero.webp',
    homeMobile: "/images/hero/HomeMobile.webp"
  },
  svgs: {
    shapeBlueSvg: "/images/svgs/shapeBlue.svg",
    shapeOrangeSvg: "/images/svgs/shapeOrange.svg",
    shapeGreenSvg: "/images/svgs/shapedeepgreen.svg",
    shapeGraySvg: "/images/svgs/shapeGray.svg",
    bookAppointment: "/images/svgs/Book-Your-Health-Checkup.svg",
    findDoctor: "/images/svgs/Find-Doctor.svg",
    ourHospitalLocations: "/images/svgs/OurHospitalLocations.svg",
    ourSpecialties: "/images/svgs/OurSpecialties.svg",
    Cancer: "/images/svgs/Cancer.svg",
    Cardiac: "/images/svgs/Cardiac.svg",
    Neuro: "/images/svgs/Neuro.svg",
    Ortho: "/images/svgs/Orthopedics.svg",
    shapeCard: "/images/svgs/shapeCArd.svg",
    cardiology1: "/images/svgs/cardiology1.svg",
    neurologist1: "/images/svgs/neurologist1.svg",
    oncology1: "/images/svgs/oncology1.svg",
    orthopedic1: "/images/svgs/orthopedic1.svg",
    gastroenterology1: "/images/svgs/gastroenterology1.svg",
    map: "/images/svgs/map.svg",

  },
  hospitals: {
    ahmedabad: '/images/hospitals/Ahmedabad.svg',
    gurugram: '/images/hospitals/Gurugram.svg',
    faridabad: '/images/hospitals/Faridabad.svg',
    saudiArabia: '/images/hospitals/Saudi-Arabia.svg',
    surat: '/images/hospitals/Surat.svg',
    vadodara: '/images/hospitals/Vadodara.svg',

  },
  technologies: {
    petCt: '/images/technologies/pet-ct.webp',
    cuvis: '/images/technologies/CUVIS.webp',
    laparoscopic: '/images/technologies/Laparoscopic.webp',
    biosensor: '/images/technologies/biosensor.webp',
  },
  packages: {
    health360: '/images/packages/360health.svg',
    healthyHeart: '/images/packages/Healthy.svg',
    specialScreening: '/images/packages/SpecialScreening.svg',
  },
  testimonials: {
    patient1: '/images/testimonials/patient-1.webp',
    patient2: '/images/testimonials/patient-4.webp',
    patient3: '/images/testimonials/patient-3.webp',
    doublesmiling: '/images/testimonials/doublesmiling.gif',
    hand: '/images/testimonials/hand.gif',
    smiling: '/images/testimonials/smiling.gif',
    star: '/images/testimonials/star.gif',
  },
  news: {
    main: '/images/news/main.png',
    news1: '/images/news/news1Img.png',
    news2: '/images/news/news2.png',
    news3: '/images/news/news3.png',
    news4: '/images/news/news4.png',
  },
  blogs: {
    blog1: '/images/blogs/blog1.svg',
    blog2: '/images/blogs/blog2.svg',
    blog3: '/images/blogs/blog3.svg',
  },
  countries: {
    bd: '/images/countries/bd.svg',
    np: '/images/countries/np.svg',
    kz: '/images/countries/kz.svg',
    iq: '/images/countries/iq.svg',
    om: '/images/countries/om.svg',
    ug: '/images/countries/ug.svg',
    tj: '/images/countries/tj.svg',
    mm: '/images/countries/mm.svg',
    gb: '/images/countries/gb.svg',
    us: '/images/countries/us.svg',
    uz: '/images/countries/uz.svg',
    ke: '/images/countries/ke.svg',
    fj: '/images/countries/fj.svg',
    ng: '/images/countries/ng.svg',
    tz: '/images/countries/tz.svg',
    mu: '/images/countries/mu.svg',
    ae: '/images/countries/ae.svg',
    ye: '/images/countries/ye.svg',
    et: '/images/countries/et.svg',
    rw: '/images/countries/rw.svg',
    cm: '/images/countries/cm.svg',
  },
  common: {
    worldMap: '/images/common/world-map.svg',
  },
  menusIcon: {
    BariatricSurgeryIcon: "/images/menusIcon/BariatricSurgeryIcon.svg",
    BoneMarrowIcon: "/images/menusIcon/BoneMarrowIcon.svg",
    CancerCareIcon: "/images/menusIcon/CancerCareIcon.svg",
    CardiacSciencesIcon: "/images/menusIcon/CardiacSciencesIcon.svg",
    ClinicalPsychologyIcon: "/images/menusIcon/ClinicalPsychologyIcon.svg",
    DentalIcon: "/images/menusIcon/DentalIcon.svg",
    DermatologyIcon: "/images/menusIcon/DermatologyIcon.svg",
    DiabeticFootIcon: "/images/menusIcon/DiabeticFootIcon.svg",
    GastroenterologyIcon: "/images/menusIcon/GastroenterologyIcon.svg",
    LiverTransplantIcon: "/images/menusIcon/LiverTransplantIcon.svg",
    NeurosciencesIcon: "/images/menusIcon/NeurosciencesIcon.svg",
    OrthopaedicsIcon: "/images/menusIcon/OrthopaedicsIcon.svg",
    RenalSciencesIcon: "/images/menusIcon/RenalSciencesIcon.svg",
    RheumatologyIcon: "/images/menusIcon/RheumatologyIcon.svg",
  },
  footer: {
    apple: "/images/svgs/apple.webp",
    googlePlay: "/images/svgs/google-play.webp",
  }
};
