export const IMAGES = {
  logo: {
    main: '/images/logo/logo.webp',
  },
  hero: {
    home: '/images/hero/home-hero.webp',
    homeMobile: "/images/hero/HomeMobile.webp"
  },
  svgs:{
    shapeBlueSvg:"/images/svgs/shapeBlue.svg",
    shapeOrangeSvg:"/images/svgs/shapeOrange.svg",
    shapeGreenSvg:"/images/svgs/shapedeepgreen.svg",
    shapeGraySvg:"/images/svgs/shapeGray.svg",
    bookAppointment:"/images/svgs/Book-Your-Health-Checkup.svg",
    findDoctor:"/images/svgs/Find-Doctor.svg",
    ourHospitalLocations:"/images/svgs/OurHospitalLocations.svg",
    ourSpecialties:"/images/svgs/OurSpecialties.svg",
    Cancer:"/images/svgs/Cancer.svg",
    Cardiac:"/images/svgs/Cardiac.svg",
    Neuro:"/images/svgs/Neuro.svg",
    Ortho:"/images/svgs/Orthopedics.svg",
    shapeCard:"/images/svgs/shapeCArd.svg",
    cardiology1:"/images/svgs/cardiology1.svg",
    neurologist1:"/images/svgs/neurologist1.svg",
    oncology1:"/images/svgs/oncology1.svg",
    orthopedic1:"/images/svgs/orthopedic1.svg",
    gastroenterology1:"/images/svgs/gastroenterology1.svg",
    map:"/images/svgs/map.svg",
    
  },
  hospitals: {
    ahmedabad: '/images/hospitals/ahmedabad.svg',
    gurgaon: '/images/hospitals/gurgaon.svg',
    faridabad: '/images/hospitals/faridabad.svg',
    surat: '/images/hospitals/surat.svg',
    kolkata: '/images/hospitals/kolkata.svg',
    noida: '/images/hospitals/noida.svg',
    mumbai: '/images/hospitals/mumbai.svg',
    delhi: '/images/hospitals/delhi.svg',
  },
  technologies: {
    petCt: '/images/technologies/pet-ct.webp',
    cuvis: '/images/technologies/CUVIS.webp',
    laparoscopic: '/images/technologies/Laparoscopic.webp',
    biosensor: '/images/technologies/biosensor.webp',
  },
  packages: {
    health360: '/images/packages/360health.svg',
    healthyHeart: '/images/packages/Healthy.svg',
    maternityCare: '/images/packages/MaternityCare.svg',
    specialScreening: '/images/packages/SpecialScreening.svg',
  },
  testimonials: {
    patient1: '/images/testimonials/patient-1.svg',
    patient2: '/images/testimonials/patient-2.jpg',
    patient3: '/images/testimonials/patient-3.svg',
  },
  news: {
    main: '/images/news/news-main.svg',
    news1: '/images/news/news-1.svg',
    news2: '/images/news/news-2.svg',
    news3: '/images/news/news-3.svg',
    news4: '/images/news/news-4.svg',
  },
  blogs: {
    cardiac: '/images/blogs/blog-cardiac.svg',
    robotic: '/images/blogs/blog-robotic.svg',
    brain: '/images/blogs/blog-brain.svg',
  },
  countries: {
    bd: '/images/countries/bd.svg',
    np: '/images/countries/np.svg',
    kz: '/images/countries/kz.svg',
    iq: '/images/countries/iq.svg',
    om: '/images/countries/om.svg',
    ug: '/images/countries/ug.svg',
    tj: '/images/countries/tj.svg',
    mm: '/images/countries/mm.svg',
    gb: '/images/countries/gb.svg',
    us: '/images/countries/us.svg',
    uz: '/images/countries/uz.svg',
    ke: '/images/countries/ke.svg',
    fj: '/images/countries/fj.svg',
    ng: '/images/countries/ng.svg',
    tz: '/images/countries/tz.svg',
    mu: '/images/countries/mu.svg',
    ae: '/images/countries/ae.svg',
    ye: '/images/countries/ye.svg',
    et: '/images/countries/et.svg',
    rw: '/images/countries/rw.svg',
    cm: '/images/countries/cm.svg',
  },
  common: {
    worldMap: '/images/common/world-map.svg',
  },
};
